server {
    listen 80;
    server_name localhost;

    root /var/www/TF01;
    index index.html;

    access_log /var/log/nginx/TF01_access.log;
    error_log /var/log/nginx/TF01_error.log;
    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}